language: python
python:
  - "2.7"
  - "3.6"

script:
     # install the package and test
     - pip install pipenv
     - bash easy_install.sh
     - pip install -e .[tests]
     - py.test --pep8 -m pep8 -n8
     - py.test -n8
     - ./test_pylint

