language: python
python:
  - "2.7"
  - "3.6"

script:
     # install the package and test
     - pip install pipenv
     - bash dep/bc_exploration/scripts/build_exploration
     - pipenv install --skip-lock
     - pip install -e .[tests]
     - py.test --pep8 -m pep8 -n8
     - py.test -n8
     - ./test_pylint

